Bug Fix - #129
serhiisol/node-decorators pull request #130
Opened 2023-01-24 11:28 UTC by vikaskandari

2023-01-24 11:37 UTC, vikaskandari commented
We were actually sending blank response even if controller method is not returning any value or undefined which was causing this issue, 

when we were using Next function in controller instead of returning any value server was sending blank response and also calling other controllers as we were using next function, but in other controller when we returned a value it was not sending any response because we have a headers already sent check which prevented it form throwing any error or any response.

To fix this i simply added a  undefined validation check if controller does not return anything or returns undefined it will not send any response , 

this way if controller uses a next function it will pass the request to next controller  and if controller is not using next function it will not return any response thus hanging response till timeout.

2023-01-24 12:01 UTC, vikaskandari commented
Added a fix on second commit  - When server returns a undefined promise for example if we use a async method like 

```typescript
@Get("/")
async getTest(@Next() next : NextFunction){
 next();
}
```

routeHandler receives promise in result so i have set a validation if promise resolves as undefined it will not send any response

2023-01-30 08:37 UTC, serhiisol commented
Could you revert di package.lock ?

2023-01-30 08:39 UTC, serhiisol requested changes

2023-01-30 08:39 UTC, serhiisol commented on express/src/express.ts
> +    if (typeof result !== "undefined") {
could you add 
```typescript
if (typeof result === 'undefined') {
  return;
}
```

statement instead to reduce nesting?

2023-01-30 08:39 UTC, serhiisol commented on express/src/express.ts
> +          if (!res.headersSent && typeof r !== "undefined") {
Could you replace double quotes with single?

2023-01-31 11:57 UTC, closed without merging